Computational modeling in python, SoSe2022 

# More on: Lists, tuples, arrays etc. in python

Lists contain several objects that can be anything:

In [1]:
mylist1 = ['a','b','c','d','e','f']
print('A list with strings:',mylist1)
a=5
b=6
c=5682.3
mylist2 = [a,b,c]
print('A list with integers and floats:',mylist2)
mylist3 = ['you','with','May','4th','the','be']
print('Something garbled:',mylist3)

A list with strings: ['a', 'b', 'c', 'd', 'e', 'f']
A list with integers and floats: [5, 6, 5682.3]
Something garbled: ['you', 'with', 'May', '4th', 'the', 'be']


We can access the elements of a list using the index operator <code>[]</code> and zero-based indices:

In [2]:
print("mylist1[1]:     ", mylist1[1])     # second element
print("mylist1[-1]:    ", mylist1[-1])    # last element 
print("mylist1[-1]:    ", mylist1[-2])    # second-last element
print("mylist1[0:2]:   ", mylist1[0:2])   # [m:n] slices of lists elements m to n-1
print("mylist1[1:]:    ", mylist1[1:])    # [n:] elements from n and above
print("mylist1[1:5:2]: ", mylist1[1:5:2]) # [m:n:l] elements from m to n-1 step l
print("mylist1[::2]:   ", mylist1[::2])   # [::l] all elements step l

mylist1[1]:      b
mylist1[-1]:     f
mylist1[-1]:     e
mylist1[0:2]:    ['a', 'b']
mylist1[1:]:     ['b', 'c', 'd', 'e', 'f']
mylist1[1:5:2]:  ['b', 'd']
mylist1[::2]:    ['a', 'c', 'e']


We cannot perform arithmetic operations on lists with floats:

In [3]:
5.8*mylist2

TypeError: can't multiply sequence by non-int of type 'float'

But we can perform operations on lists with integers <code>n</code> which will return a new list with <code>n</code> times as many elements: The operation acts on the list object, not on its elements. 

In [4]:
5*mylist2

[5, 6, 5682.3, 5, 6, 5682.3, 5, 6, 5682.3, 5, 6, 5682.3, 5, 6, 5682.3]

We can perform arithmetic operations on single the elements of a list:

In [5]:
5.8*mylist2[1]

34.8

Lists themselves can also contain lists (and are called nested lists):

In [6]:
mylist4 = [mylist1,mylist2,mylist3]
print("mylist4: ", mylist4)
mylist5 = [[1,2,3],['f','d','s','a']]
print("mylist5: ", mylist5)

mylist4:  [['a', 'b', 'c', 'd', 'e', 'f'], [5, 6, 5682.3], ['you', 'with', 'May', '4th', 'the', 'be']]
mylist5:  [[1, 2, 3], ['f', 'd', 's', 'a']]


Elements in nested lists are accessed with consecutive index operators. The first index-operator acts on the outer list and returns an inner list. We can operate on the inner list immediately with a second index operator (or any other operation supported by the object returned by the first index operator).

In [7]:
print("mylist5[0][0]:  ", mylist5[0][0])
print("mylist5[1][-1]: ", mylist5[1][-1])
print("mylist5[1][2]:  ", mylist5[1][2])

mylist5[0][0]:   1
mylist5[1][-1]:  a
mylist5[1][2]:   s


One can even put a function into the list. This can be useful to pass functionality around between different parts of code. 

In [8]:
def myfunc():
    print("I am a function in a list")
    
myflist = [myfunc,]

print("mylist[0]: ", myflist[0])

# We can access the function with the index 
# operator. The index-operator returns the function object. 
# To execute the function we just need to add round brackets:
# one also says 'calling the function'. 
# Round brackets 'call' the function. 

myflist[0]()
# ------^    returns function
# ---------^ calls the function


mylist[0]:  <function myfunc at 0x7f4ff415d430>
I am a function in a list


Elements in lists can be changed:

In [9]:
print("mylist2: ", mylist2)
mylist2[1]=83.5
print("mylist2: ", mylist2)

mylist2:  [5, 6, 5682.3]
mylist2:  [5, 83.5, 5682.3]


Lists can be extended using append():

In [10]:
mylist1.append('d')
print("mylist1: ", mylist1)
mylist6=[]
mylist6.append(mylist1)
mylist6.append(mylist2)
print("mylist6: ", mylist6)

mylist1:  ['a', 'b', 'c', 'd', 'e', 'f', 'd']
mylist6:  [['a', 'b', 'c', 'd', 'e', 'f', 'd'], [5, 83.5, 5682.3]]


Lists can be extended without generating nested lists using extend:

In [11]:
print("mylist1: ", mylist1)
mylist1.extend('e') # single element
print("mylist1: ", mylist1)

mylist6=[]
print("mylist6: ", mylist6)
mylist6.extend(mylist1) # append elements from list
mylist6.extend(mylist2)
print("mylist6: ", mylist6)

mylist1:  ['a', 'b', 'c', 'd', 'e', 'f', 'd']
mylist1:  ['a', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist6:  []
mylist6:  ['a', 'b', 'c', 'd', 'e', 'f', 'd', 'e', 5, 83.5, 5682.3]


We can also insert items:

In [12]:
# assignment: the same list is not known
# by twe different names
mylist7 = mylist1
print("mylist7: ", mylist7)

# insert an element at position 1. 
mylist7.insert(1,'x')
print("mylist7: ", mylist7)
# insert an element at position 1. 
mylist7.insert(1,'x')


print("mylist7: ", mylist7)
print("mylist1: ", mylist1)

mylist1 is mylist7
# note these point to the same memory address because 
# we used the '=' operation above

mylist7:  ['a', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist7:  ['a', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist7:  ['a', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist1:  ['a', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']


True

In [13]:
# create an empty list

mylist7 = []

# extend the list with mylist1
mylist7.extend(mylist1)

# they are not the same object, but have the same contents
print("mylist1 is mylist7: ", mylist1 is mylist7)

print("mylist7: ", mylist7)
mylist7.insert(1,'x')
print("mylist7: ", mylist7)
mylist7.insert(1,'x')
print("mylist7: ", mylist7)
print("mylist1: ", mylist1)

# adding elements to mylist7 does not change mylist1

mylist1 is mylist7:  False
mylist7:  ['a', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist7:  ['a', 'x', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist7:  ['a', 'x', 'x', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist1:  ['a', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']


Deleting items from lists:

In [14]:
print("mylist7: ", mylist7)

# delete an element using the index operator and the del command
del mylist7[0]
print("mylist7: ", mylist7)

# delete the first matching element
# (results in error if the element does not exist):
mylist7.remove('x')
print("mylist7: ", mylist7)

# remove an element using its position 
# and assign it to a variable:
lastelem = mylist7.pop(-1) # remove last element
print("mylist7: ", mylist7)
print("lastelem: ", lastelem)


mylist7:  ['a', 'x', 'x', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist7:  ['x', 'x', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist7:  ['x', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd', 'e']
mylist7:  ['x', 'x', 'x', 'b', 'c', 'd', 'e', 'f', 'd']
lastelem:  e


Python List Methods:

<code>append() </code>  - Add an element to the end of the list\
<code>clear()  </code>  - Removes all items from the list\
<code>copy()   </code>  - Returns a shallow copy of the list\
<code>count()  </code>  - Returns the count of number of items passed as an argument\
<code>extend() </code>  - Add all elements of a list to the another list\
<code>index()  </code>  - Returns the index of the first matched item\
<code>insert() </code>  - Insert an item at the defined index\
<code>pop()    </code>  - Removes and returns an element at the given index\
<code>remove() </code>  - Removes an item from the list\
<code>reverse()</code>  - Reverse the order of items in the list\
<code>sort()   </code>  - Sort items in a list in ascending order\



To find out about attributes (functions and variables) defined for an 
object or module use the <code>dir()</code> command:

In [15]:
dir(mylist7)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

The double underscore functions are special functions that implement certain functionality. We will look at them in more detail later in the course.
In a Notebook you can also use the tabulator key &#11134; for auto-complete. Start typing and hit &#11134; (sometimes one needs to hit tab twice).

In [16]:
# move the curser behind the 'myli' and hit tab (twice):
mylist7

# move the curser behind the dot and hit tab (twice):
mylist7.append()

# move the curser behind the c and hit tab (twice):
mylist7.clear()

TypeError: list.append() takes exactly one argument (0 given)

## Looping over lists

There are two kinds of loops in python: while-loop and for-loop.

### while-loop

Syntax: 

<code>
while condition:
    indented_code_block
</code>

The indented code block is executed over and over as long as the condition evaluates to <code>True</code>. One needs to make sure that the condition evaluates to <code>False</code> at some point, otherwise the loop will be infinite. 
    

In [17]:
mylist1 = ['a','b','c','d','e','f'] # mylist got a bit long now so start over

j=0 # needs to be initialized
while j < len(mylist1): # as long as condition is fulfilled, loop is executed
    print(mylist1[j])
    j = j+1

a
b
c
d
e
f


In [18]:
j=0
x = 'y'
print("mylist1: ", mylist1)
while x != 'c':
    print("before assignment: j={}, x={}".format(j,x))    
    x=mylist1[j]
    j = j+1
    print("after assignment:  j={}, x={}".format(j,x))

mylist1:  ['a', 'b', 'c', 'd', 'e', 'f']
before assignment: j=0, x=y
after assignment:  j=1, x=a
before assignment: j=1, x=a
after assignment:  j=2, x=b
before assignment: j=2, x=b
after assignment:  j=3, x=c


In [19]:
j = 0
mx=10
while j < mx:
    print(j)
    j=j+1 # what happens if we forget to add 1 to j? 
          # (use Kernel -> Interrupt to stop infinite loops)

0
1
2
3
4
5
6
7
8
9


### for-loop

Syntax: 

<code>
for element in sequence:
    indented_code_block_using_element
</code>



The <code>range</code> function returns a sequence of integers and is often used in for-loops.

Syntax: <code>range(start=0, stop, step=1)</code> 

<code>start</code>  and <code>step</code>  are optional parameters. Their default value is indicated with the <code>=</code> in the syntax above.

In [20]:
# return a sequence of integers starting at 0, ending at 5 (not including 5)

for j in range(5):
    print(j)

0
1
2
3
4


In [21]:
# return a sequence of integers starting at 2, ending at 5 (not including 5)

for j in range(2,5):
    print(j)

2
3
4


In [22]:
# return a sequence integers starting at 1, ending at 5 (not including 5) in steps of 2

for j in range(1,5,2):
    print(j)

1
3


In [23]:
# we can feed the result of some other function directly into range(),
# by putting it into argument list of range: here the len() function.
# The output of the call to len() is then then input of range(), here the
# number of elements in mylist1. 

for j in range(len(mylist1)):
    print(j,mylist1[j])

0 a
1 b
2 c
3 d
4 e
5 f


In [24]:
# we can loop directly over list elements because lists are 'iterable'

for m in mylist1:
    print(m, mylist1.index(m))

a 0
b 1
c 2
d 3
e 4
f 5


In [25]:
# the enumerate function returns a sequence of index-element pairs.
# (it is actually a tuple of index and element
# which is unpacked in two variables - see below)
# Here the index is assigned to the variable j and the element to 
# variable mm. 

for j,mm in enumerate(mylist1):
    print(j,mm) # mm = mylist1[j]
    

0 a
1 b
2 c
3 d
4 e
5 f


## Tuples
Tuples are like lists but the elements cannot be changed:

In [26]:
# empty tuple 
mytuple1 = () 
print(mytuple1)

# tuple of integer literals
mytuple2 = (1, 2, 3)
print(mytuple2)

# tuple of various types
mytuple3 = (1, 'a', 5673.4)
print(mytuple3)

# nested tuple
mytuple4 = (mytuple1,mytuple2,mytuple3)
print(mytuple4)

()
(1, 2, 3)
(1, 'a', 5673.4)
((), (1, 2, 3), (1, 'a', 5673.4))


Tuples can also be created without the parentheses (tuple packing):

In [27]:
mytuple5 = 'h', 3, 5.8  # comma separated literals 
print(mytuple5)

('h', 3, 5.8)


The reverse is also possible (tuple unpacking):

In [28]:
a, b, c = mytuple5
print(a)
print(b)
print(c)

h
3
5.8


We have actually seen tuple packing and unpacking in problem 1 already without knowing about it:

In [29]:
# from problem 1:

from numpy import *

def area_circ(r):
    
    a = zeros(len(r))
    c = zeros(len(r))
    
    for i,myr in enumerate(r):
        # ^--- tuple unpacking
        
        a[i] = pi * myr**2
        c[i] = 2.0 * pi * myr
        
    return a, c  # tuple packing

r = linspace(0,10,11)


area, circ = area_circ(r) # tuple unpacking

In [30]:
# for tuples with a single element a comma is mandatory
my_tuple = ("hello")   # without a comma this is an arythmetic bracket
print(type(my_tuple))  # <class 'str'>  not a tuple

# Creating a tuple having one element
my_tuple = ("hello",)
print(type(my_tuple))  # <class 'tuple'>

# Parentheses is optional
my_tuple = "hello",
print(type(my_tuple))  # <class 'tuple'>

<class 'str'>
<class 'tuple'>
<class 'tuple'>


Tuples are immutable:

In [ ]:
print(mytuple2[0])
mytuple2[0]=10

## Dictionaries

Dictionaries are ordered key-value pairs, they are changeable but do not allow duplicates of keys.

Dictionaries are created with curly brackets:


In [ ]:
# empty dictionary
mydict = {}

# create a dictionary with three key-value pairs. 
# using a comma separated list of the form key:value
mydict = {"key":"value", 2:2.0, "x":print}
print("mydict", mydict)

Dictionary keys can be of any type but must be immutable (lists for instance cannot be used as keys, but tuples can). Often keys are strings, for instance names of parameters etc.

We can access a value using the index operator and the respective key:

In [ ]:
mydict[2] # not the third element but the key 'integer 2'

In [ ]:
mydict["key"]

In [ ]:
# assigning a new key inserts it into the dictionary:
mydict["newkey"] = "hello world"
print("mydict: ", mydict)

A list of all keys of a dictionary:

In [ ]:
mydict.keys()

In [ ]:
# looping through dictionaries by keys
for key in mydict:
    print(key, mydict[key])

In [ ]:
# Same effect as using the keys() function
for key in mydict.keys():
    print(key, mydict[key])

In [ ]:
# looping through dictionaries by items (tuples of key-value pairs)
for item in mydict.items():
    print(item)

In [ ]:
# looping through dictionaries by values
for val in mydict.values():
    print(val)


Concatenation of two dictionaries:

In [ ]:
mydict2 = {"a":"b", "newkey":"grml"}


# the '**' means: unpack mydict and mydict2 into key=value pairs
# The key-value pairs are then passed to the initialization
# routine of dictionaly and are used to create a new dictionary.

mydict3 = {**mydict, **mydict2}
print(mydict3)

# python 3.9 and higher:
mydict3 = mydict | mydict2 # | binary OR operator
print(mydict3)

# note that this will overwrite existing keys of the first dictionary 
# here: 'newkey': 'grml' overwrites 'newkey': 'hello world'


Dictionaries do not implement the <code>+</code> operation because  it would not be a true 'plus' if the dictionaries have identical keys. This would either result in a conflict or in overwriting as above. One rather needs to 'merge' the dictionaries. 


## Arrays

- Arrays are used for mathematical operations
- Requires numpy - python itself has only lists
- <b>All elements in an array have the same data type</b>

In [20]:
# import everything from numpy (done above)
from numpy import *

length = 10

# create an array of length 10 filled with zeros (default data type: 64-bit float)
array1 = zeros(length)
print("array1 (zeros): ", array1)

# create an array of length 10 filled with ones
array1 = ones(length)
print("array1 (ones): ", array1)

# create a 2D-array (matrix) of size 3x3 but do not  
# initialize it. The numbers in the array are random 
# and can be anything. Use with care!
length1 = 3
array1 = empty([length1,length1])
print("array1 (empty): ", array1)



array1 (zeros):  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array1 (ones):  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array1 (empty):  [[4.63740417e-310 0.00000000e+000 4.63740417e-310]
 [8.87360115e+294 6.91600174e-310 4.63740417e-310]
 [6.24014601e-236 6.91600174e-310 3.95252517e-322]]


In [18]:
# we can convert a list to an array
myarray1 = array([1,2,3,4,5,6,7,8,9,10])
print("myarray1: ", myarray1)
print("type(myarray1): ", type(myarray1))

# the dtype attribute holds information on the kind of 
# data stored in the array.
# numpy will try to guess the correct data type. 
# we passed a list of integers, so it returned an integer array.
# try changing one element to a float and repeat. 
print("myarray1.dtype: ", myarray1.dtype)

# the data type can be specified explicitly:
myarray1 = array([1,2,3,4,5,6,7,8,9,10],dtype=complex)
print("myarray1: ", myarray1)
print("myarray1.dtype: ", myarray1.dtype)

myarray1:  [ 1  2  3  4  5  6  7  8  9 10]
type(myarray1):  <class 'numpy.ndarray'>
myarray1.dtype:  int64
myarray1:  [ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]
myarray1.dtype:  complex128


Arrays can contain different types of data. The type is determined automatically unless it is explicitly declared.

In [19]:
myarray2 = zeros(length,dtype=ndarray)
print("myarray2: ", myarray2)
print("myarray2.dtype: ", myarray2.dtype)
myarray2[0]=myarray1
print("myarray2: ", myarray2)

myarray2:  [0 0 0 0 0 0 0 0 0 0]
myarray2.dtype:  object
myarray2:  [array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
         8.+0.j,  9.+0.j, 10.+0.j])                                    0 0
 0 0 0 0 0 0 0]


The elements of an array can themselves be arrays (or other objects).

Array indexing is similar to list indexing: <code>x[start:stop:step]</code>

In [21]:
print("myarray1[0:length:2]: ", myarray1[0:length:2])

# this is the same as

print("myarray1[::2]: ", myarray1[::2])

# if start and stop coincide with first and last element of the array, they need not to be given

print("myarray1[::-2]: ", myarray1[::-2])

# a negative step reverses the order.

myarray1[0:length:2]:  [1.+0.j 3.+0.j 5.+0.j 7.+0.j 9.+0.j]
myarray1[::2]:  [1.+0.j 3.+0.j 5.+0.j 7.+0.j 9.+0.j]
myarray1[::-2]:  [10.+0.j  8.+0.j  6.+0.j  4.+0.j  2.+0.j]


And arrays can be reshaped:

In [25]:
# 9-element vector
myarray2 = array([1,2,3,4,5,6,7,8,9])
print("myarray2: ", myarray2)

# 3x3 matrix
myarray3 = myarray2.reshape(3,3)
print("myarray3: \n", myarray3)

# the arrays are not the same object
print("myarray2 is myarray3: ", myarray2 is myarray3)

# the reshape operation returns a different 'view'
# on the array. 
# but they still share the same data buffer
myarray2[0] = -10
print("myarray3: ", myarray3)

myarray2:  [1 2 3 4 5 6 7 8 9]
myarray3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
myarray2 is myarray3:  False
myarray3:  [[-10   2   3]
 [  4   5   6]
 [  7   8   9]]


We can access single elements of the matrix with the index operator. Note that the matrix is organized as an array of arrays:

In [26]:
myarray3[1][2]

6

In [27]:
# the index operator can take two parameters 
myarray3[1,2]

6

In [28]:
# we can access sub-arrays 
myarray3[1] # returns a row of the matrix

array([4, 5, 6])

Very useful functions are <code>arange</code> and <code>linspace</code>. </ode>arange</code> returns values between <code>start</code>, <code>stop</code> with a <code>dx</code> where the last point (<code>stop</code> ) is not included; whereas <code>linspace</code> returns values between <code>start</code>, <code>stop</code>  with number of grid points where the last point (<code>stop</code>) is included.

In [29]:
myarray2 = arange(1,10)
print("myarray2: ", myarray2)
print("arange(9): ", arange(9))
print("arange(0,9,0.5): ", arange(0,9,0.5))

myarray3 = linspace(0,11,12)
print("myarray3: ", myarray3)
myarray4 = myarray3.reshape(3,4)
print("myarray4: ", myarray4)
print("linspace(2,5,4): ", linspace(2,5,4))

# Note that arange defaults to dtype=int for integer input. 
# One can give an explicit dtype in both, arange and linspace

myarray2:  [1 2 3 4 5 6 7 8 9]
arange(9):  [0 1 2 3 4 5 6 7 8]
arange(0,9,0.5):  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
myarray3:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
myarray4:  [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
linspace(2,5,4):  [2. 3. 4. 5.]


Arrays can be concatenated:

In [ ]:
# arrays can be concatenated:
print("concatenate([myarray2,myarray2]): ", concatenate([myarray2,myarray2]))

# But note that other than for lists the + operation
# results in element-wise + and not in concatenation.
print("myarray2 + myarray2: ", myarray2 + myarray2)
print("myarray2 * myarray2: ", myarray2 * myarray2)

There is a large number of functions available for operations on arrays. See \
https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html \
https://docs.scipy.org/doc/numpy/reference/routines.sort.html \
https://docs.scipy.org/doc/numpy/reference/routines.statistics.html 
            
For an overview see https://docs.scipy.org/doc/numpy/reference/routines.html.


## There are also <code>sets</code> which we will consider later.

# Task 1

Find out how many colors there are in the mycolors list below. Using loop structures, case selection and list indexing where required, find out
1. how many colors have three letters or less in their name?
2. how many colors have four letters?
3. how many colors have five letters?
4. how many colors have six letters?
5. how many colors have seven or more letters?

You can find the number of letters in a string using the len() function.

Create an array that contains the above 1., 2., 3., 4., 5. numbers. Sum over all elements in the array using a loop, and using a numpy intrinsic function that you can find at one of the links above. Calculate the mean average value over all elements in the array using a loop and using a numpy intrinsic function.

In [30]:
# import some colors from matplotlib

from matplotlib import colors as mcolors

# BASE_COLORS and CSS4_COLORS are both dictionaries,
# key: color name; value: RGB value 

# concatenate the two dictionaries into one
colors = {**mcolors.BASE_COLORS, **mcolors.CSS4_COLORS}

colors["black"] # string of red,green,blue values in hexadecimal format

'#000000'

In [31]:
colorlist = []

# loop through the dictionary
for name, color in colors.items():

    # convert the hex RGB code to three numbers and alpha (opacity)
    rgba = mcolors.to_rgba(color)
    
    # convert the numerical RGB value to hue, saturation, value (HSV)
    # with [:3] we skip opacity because mcolors.rgb_to_hsv
    # cannot digest it
    tpl = (tuple(mcolors.rgb_to_hsv(rgba[:3])), name)
    
    # append the tuple to the list
    colorlist.append(tpl)
    
# Lets see how this looks for sone color
elem = 10
print('HSV: ', colorlist[elem])
print('RGB: ', colors[colorlist[elem][1]],colorlist[elem][1] )

HSV:  ((0.5, 1.0, 1.0), 'aqua')
RGB:  #00FFFF aqua


In [32]:
# sort the list by hue, saturation, value and name
by_hsv = sorted(colorlist)
    
# [x for x in something] is an implicit iteration 
# that returns a new list of elements x in something. 
# here it is used to extract the names from the 

mycolors = [name for hsv, name in by_hsv]

print(mycolors)

['black', 'k', 'dimgray', 'dimgrey', 'gray', 'grey', 'darkgray', 'darkgrey', 'silver', 'lightgray', 'lightgrey', 'gainsboro', 'whitesmoke', 'w', 'white', 'snow', 'rosybrown', 'lightcoral', 'indianred', 'brown', 'firebrick', 'maroon', 'darkred', 'r', 'red', 'mistyrose', 'salmon', 'tomato', 'darksalmon', 'coral', 'orangered', 'lightsalmon', 'sienna', 'seashell', 'chocolate', 'saddlebrown', 'sandybrown', 'peachpuff', 'peru', 'linen', 'bisque', 'darkorange', 'burlywood', 'antiquewhite', 'tan', 'navajowhite', 'blanchedalmond', 'papayawhip', 'moccasin', 'orange', 'wheat', 'oldlace', 'floralwhite', 'darkgoldenrod', 'goldenrod', 'cornsilk', 'gold', 'lemonchiffon', 'khaki', 'palegoldenrod', 'darkkhaki', 'ivory', 'beige', 'lightyellow', 'lightgoldenrodyellow', 'olive', 'y', 'yellow', 'olivedrab', 'yellowgreen', 'darkolivegreen', 'greenyellow', 'chartreuse', 'lawngreen', 'honeydew', 'darkseagreen', 'palegreen', 'lightgreen', 'forestgreen', 'limegreen', 'darkgreen', 'g', 'green', 'lime', 'seagreen

In [ ]:
# print the color and number of letters
print(mycolors[0],len(mycolors[0]))

# Task 2

Create an array with 256 values between zero and one, including one. Reshape this array into a 2D-matrix with equal number of rows and columns (square matrix). Multiply this matrix with the identity matrix __I__.

Remember: The identity matrix is a square matrix with ones on the diagonal and zero entries everywhere else.

\begin{align}
\mathbf{I} = 
\begin{pmatrix} 
1 & 0 & 0 & \ldots & 0 \\
0 & 1 & 0 & \ldots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \ldots & 1 \\
 \end{pmatrix} 
\end{align}