Computational modeling in python, SoSe2022 

There is a large number of functions available for operations on arrays. See \
https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html \
https://docs.scipy.org/doc/numpy/reference/routines.sort.html \
https://docs.scipy.org/doc/numpy/reference/routines.statistics.html 
            
For an overview see https://docs.scipy.org/doc/numpy/reference/routines.html.


# Task 1

Find out how many colors there are in the mycolors list below. Using loop structures, case selection and list indexing where required, find out
1. how many colors have three letters or less in their name?
2. how many colors have four letters?
3. how many colors have five letters?
4. how many colors have six letters?
5. how many colors have seven or more letters?

You can find the number of letters in a string using the len() function.

Create an array that contains the above 1., 2., 3., 4., 5. numbers. Sum over all elements in the array using a loop, and using a numpy intrinsic function that you can find at one of the links above. Calculate the mean average value over all elements in the array using a loop and using a numpy intrinsic function.

In [19]:
# import some colors from matplotlib

from matplotlib import colors as mcolors

# BASE_COLORS and CSS4_COLORS are both dictionaries,
# key: color name; value: RGB value 

# concatenate the two dictionaries into one
colors = {**mcolors.BASE_COLORS, **mcolors.CSS4_COLORS}

colors["black"] # string of red,green,blue values in hexadecimal format

'#000000'

In [20]:
colorlist = []

# loop through the dictionary (using tuple unpacking)
for name, color in colors.items():

    # convert the hex RGB code to three numbers and alpha (opacity)
    rgba = mcolors.to_rgba(color)
    
    # convert the numerical RGB value to hue, saturation, value (HSV)
    # with [:3] we skip opacity because mcolors.rgb_to_hsv
    # cannot digest it
    tpl = (tuple(mcolors.rgb_to_hsv(rgba[:3])), name)
    
    # append the tuple to the list
    colorlist.append(tpl)
    
# Lets see how this looks for some color
elem = 10
print('HSV: ', colorlist[elem])
print('RGB: ', colors[colorlist[elem][1]],colorlist[elem][1] )

HSV:  ((0.5, 1.0, 1.0), 'aqua')
RGB:  #00FFFF aqua


In [21]:
# sort the list by hue, saturation, value and name
by_hsv = sorted(colorlist)
    
# [x for x in something] is an implicit iteration 
# that returns a new list of elements x in something. 
# here it is used to extract the names from the 

mycolors = [name for hsv, name in by_hsv]

print(mycolors)

['black', 'k', 'dimgray', 'dimgrey', 'gray', 'grey', 'darkgray', 'darkgrey', 'silver', 'lightgray', 'lightgrey', 'gainsboro', 'whitesmoke', 'w', 'white', 'snow', 'rosybrown', 'lightcoral', 'indianred', 'brown', 'firebrick', 'maroon', 'darkred', 'r', 'red', 'mistyrose', 'salmon', 'tomato', 'darksalmon', 'coral', 'orangered', 'lightsalmon', 'sienna', 'seashell', 'chocolate', 'saddlebrown', 'sandybrown', 'peachpuff', 'peru', 'linen', 'bisque', 'darkorange', 'burlywood', 'antiquewhite', 'tan', 'navajowhite', 'blanchedalmond', 'papayawhip', 'moccasin', 'orange', 'wheat', 'oldlace', 'floralwhite', 'darkgoldenrod', 'goldenrod', 'cornsilk', 'gold', 'lemonchiffon', 'khaki', 'palegoldenrod', 'darkkhaki', 'ivory', 'beige', 'lightyellow', 'lightgoldenrodyellow', 'olive', 'y', 'yellow', 'olivedrab', 'yellowgreen', 'darkolivegreen', 'greenyellow', 'chartreuse', 'lawngreen', 'honeydew', 'darkseagreen', 'palegreen', 'lightgreen', 'forestgreen', 'limegreen', 'darkgreen', 'g', 'green', 'lime', 'seagreen

In [22]:
# print the color and number of letters
print(mycolors[0],len(mycolors[0]))

black 5


# Solution 1

First we create an array to count the various cases and initialize it with zeros. Then we fill it with the counts: 

In [23]:
from numpy import zeros, array

# we have 5 different cases
ncases = 5

# create an integer array for the counts
counts = zeros(ncases, dtype=int)


# loop through the color names
for color in mycolors:
    
    # determine the length
    clen = len(color)
    
    # case selection
    if clen <= 3:
        counts[0] =  counts[0] + 1
    elif clen == 4:
        counts[1] =  counts[1] + 1
    elif clen == 5:
        counts[2] =  counts[2] + 1
    elif clen == 6:
        counts[3] =  counts[3] + 1
    else:
        counts[4] =  counts[4] + 1
         
print(counts)
        


[ 10  13  12  12 109]


Just as a side remark: here is an example without case selection. The advantage is that it implements the same functionality without coding each individual case. This code is much more general and can easily be modified for other case selections like counting letters from 2 and below to 8 and above just by changing two variables:

In [24]:

# we start at string length 3 or less
nstart = 3
# we end at string length 7 or more
nend = 7

# we can calculate the number of cases
ncases = nend - nstart + 1 

# create an integer array for the counts
counts = zeros(ncases, dtype=int)

# loop through the color names
for color in mycolors:
    
    # determine the length
    clen = len(color)
    
    # make sure clen is at least nstart
    clen = max(nstart,clen)
    # and at most nend
    clen = min(nend,clen)
    
    # then we can calculate the index in 
    # the counts array and add 1
    idx = clen - nstart
    counts[idx] =  counts[idx] + 1
        
print(counts)
    



[ 10  13  12  12 109]


Produce some nice output:

In [26]:
print("Numbers of letters in color names:")

for n in range(nstart,nend+1):
    idx = n - nstart
    if n == nstart:
        print(f' {n} letters and below: {counts[idx]}')
    elif  n == nend:
        print(f' {n} letters and above: {counts[idx]}')
    else:
         print(f' exactly {n} letters: {counts[idx]}')
    


Numbers of letters in color names:
 3 letters and below: 10
 exactly 4 letters: 13
 exactly 5 letters: 12
 exactly 6 letters: 12
 7 letters and above: 109


Calculating the sum and mean values of the array using loops

In [27]:
sumcounts = 0

for count in counts:
    sumcounts = sumcounts + count
    
meancounts = sumcounts / len(counts)

print('The sum of counts is', sumcounts)
print('The sum of counts is', meancounts)
    

The sum of counts is 156
The sum of counts is 31.2


Calculating the sum and mean values using intrinsic functions:

In [28]:
print('The sum of counts is', counts.sum())
print('The sum of counts is', counts.mean())

The sum of counts is 156
The sum of counts is 31.2


Some verification:

In [30]:
# this must evaluate to True
print("sum of counts == len(mycolors):", counts.sum() == len(mycolors))

sum of counts == len(mycolors): True


# Task 2

Create an array with 256 values between zero and one, including one. Reshape this array into a 2D-matrix with equal number of rows and columns (square matrix). Multiply this matrix with the identity matrix __I__.

Remember: The identity matrix is a square matrix with ones on the diagonal and zero entries everywhere else.

\begin{align}
\mathbf{I} = 
\begin{pmatrix} 
1 & 0 & 0 & \ldots & 0 \\
0 & 1 & 0 & \ldots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \ldots & 1 \\
 \end{pmatrix} 
\end{align}


# Solution 2

We have to implement a matrix - matrix multiplication: $A = B\cdot C$ with $A,B,C \in  \mathbb{R}^{n\times n}$ ( real $n$ by $n$ matrix). Let us look on how the single entries of the resulting matrix are computed:

\begin{align}
 A_{i,j} = \sum\limits_k B_{i,k}C_{k,j}
\end{align}


We therefore have to loop over all indices $i,j$ and perform a summation over $k$. 

But first lets construct the matrices. 

In [31]:
from numpy import linspace, identity, double

nn = 16
nn2 = nn**2 # = 256

lineararray = linspace(0.0, 1.0, nn2)

matrix = lineararray.reshape(nn,nn)

print(matrix)

[[0.         0.00392157 0.00784314 0.01176471 0.01568627 0.01960784
  0.02352941 0.02745098 0.03137255 0.03529412 0.03921569 0.04313725
  0.04705882 0.05098039 0.05490196 0.05882353]
 [0.0627451  0.06666667 0.07058824 0.0745098  0.07843137 0.08235294
  0.08627451 0.09019608 0.09411765 0.09803922 0.10196078 0.10588235
  0.10980392 0.11372549 0.11764706 0.12156863]
 [0.1254902  0.12941176 0.13333333 0.1372549  0.14117647 0.14509804
  0.14901961 0.15294118 0.15686275 0.16078431 0.16470588 0.16862745
  0.17254902 0.17647059 0.18039216 0.18431373]
 [0.18823529 0.19215686 0.19607843 0.2        0.20392157 0.20784314
  0.21176471 0.21568627 0.21960784 0.22352941 0.22745098 0.23137255
  0.23529412 0.23921569 0.24313725 0.24705882]
 [0.25098039 0.25490196 0.25882353 0.2627451  0.26666667 0.27058824
  0.2745098  0.27843137 0.28235294 0.28627451 0.29019608 0.29411765
  0.29803922 0.30196078 0.30588235 0.30980392]
 [0.31372549 0.31764706 0.32156863 0.3254902  0.32941176 0.33333333
  0.3372549  0.34

In [32]:
# construct the unit matrix manually:
unitmatrix = zeros((nn,nn), dtype=double)
for n in range(nn):
    unitmatrix[n,n] = 1.0

print (unitmatrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [33]:
# numpy has a function 'identity' to create unit matrices

unitmatrix = identity(nn, dtype=double)
print (unitmatrix) 

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [34]:
# let's do the matrix-matix multiplication

# set up a matrix filled with zeros:
result = zeros((nn,nn), dtype=double)

# loop over all indices i,j
for i in range(nn):
    for j in range(nn):
        # do the summation along k
        for k in range(nn):
            result[i,j] = result[i,j] + matrix[i,k] * unitmatrix[k,j]
        


### Verification

Since we performed a matrix-matrix multiplication $A\cdot I$ with the unit matrix we should have:

\begin{align}
 A\cdot I = I\cdot A = A
\end{align}

Let's test if the result fulfills this requirement:

numpy has a routine <code>allclose</code> for element wise comparison that returns True if all elements of two arrays differ at most by some epsilon (default: 1e-08 - which is approximately the square root of 
the precision of 64 bit floats). This function is useful to compare outputs of floating point operations within some precision. If a result can be calculated in different ways the different operations 
are likely to result in slightly different round off errors and a comparison with <code>==</code> would fail. 


In [36]:
from numpy import allclose

print(allclose(result, matrix))

True


In [37]:
# one can also check like this, this may evaluate to 
# false for some elements
print(result == matrix)

[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  Tr

In [39]:
# just as a side remark: numpy has a matmul routine:
from numpy import matmul

result = matmul(matrix, unitmatrix)

print(allclose(result, matrix))

# There is also an operator symbol for performing matrix-matrix multiplications:

result = matrix @ unitmatrix

print(allclose(result, matrix))

True
True
